functionality:
  name: baseline_pca
  namespace: joint_embedding_methods
  version: dev
  description: PCA dimensionality reduction.
  info:
    type: baseline
    label: "PCA"
  authors:
    - name: Robrecht Cannoodt
      email: rcannood@gmail.com
      roles: [ author, maintainer ]
      props: { github: rcannood, orcid: "0000-0003-3641-729X" }
  arguments:
    - name: "--input_mod1"
      type: "file"
      example: "dataset_mod1.h5ad"
      description: Censored dataset.
      required: true
    - name: "--input_mod2"
      type: "file"
      example: "dataset_mod2.h5ad"
      description: Censored dataset.
      required: true
    - name: "--output"
      type: "file"
      direction: "output"
      example: "output.h5ad"
      description: Dataset with predicted values for modality2.
      required: true
    - name: "--n_dims"
      type: "integer"
      default: 10
      description: Number of dimensions to output.
  resources:
    - type: r_script
      path: script.R
  tests:
    - type: r_script
      path: ../../unit_tests/test_method.R
    - path: ../../../../resources_test
platforms:
  - type: docker
    image: dataintuitive/randpy:r4.0_py3.8_bioc3.12
    setup:
      - type: r
        packages: [ irlba ]
  - type: nextflow
    labels: [ lowmem, lowtime, lowcpu ]
