functionality:
  name: r_starter_kit
  namespace: joint_embedding_starter_kits
  
  # metadata for your method
  version: dev
  description: A description for your method.
  authors:
    - name: John Doe
      email: johndoe@youremailprovider.com
      roles: [ author, maintainer ]
      props: { github: johndoe, orcid: "0000-1111-2222-3333" }
      
  # parameters
  arguments:
    # required inputs
    - name: "--input_mod1"
      type: "file"
      example: "dataset_mod1.h5ad"
      description: Censored dataset.
      required: true
    - name: "--input_mod2"
      type: "file"
      example: "dataset_mod2.h5ad"
      description: Censored dataset.
      required: true
    # required outputs
    - name: "--output"
      type: "file"
      direction: "output"
      example: "output.h5ad"
      description: Dataset with predicted values for modality2.
      required: true
    # Method-specific parameters. Change these to expose parameters of your method to Nextflow (optional)
    - name: "--distance_method"
      type: "string"
      default: "spearman"
      description: The distance method to use. Possible values are euclidean, pearson, spearman and others.
    - name: "--n_pcs"
      type: "integer"
      default: 4
      description: Number of principal components to use.
      
  # files your script needs
  resources:
    - type: r_script
      path: script.R
  
  # resources for unit testing your component
  tests:
    - type: r_script
      path: test.R
    - path: sample_data
      
# target platforms
platforms:

  # By specifying 'docker' platform, viash will build a standalone
  # executable which uses docker in the back end to run your method.
  - type: docker
    # you need to specify a base image that contains at least
    # R, python, bash and the 'anndata' python package.
    image: dataintuitive/randpy:r4.0_py3.8_bioc3.12
    # You can specify additional dependencies with 'setup'. 
    # See https://viash.io/docs/reference_config/platform-docker/#setup-list
    # for more information on how to add more dependencies.
    setup:
      # - type: apt
      #   packages:
      #     - bash
      # - type: python
      #   packages:
      #     - scanpy
      - type: r
        packages:
          - lmds

  # By specifying a 'nextflow', viash will also build a viash module
  # which uses the docker container built above to also be able to 
  # run your method as part of a nextflow pipeline.
  - type: nextflow
    labels: [ lowmem, lowtime, lowcpu ]
