functionality:
  name: msle
  namespace: predict_modality_metrics
  version: dev
  description: Calculating basic metrics for the predict modality task.
  authors:
    - name: Robrecht Cannoodt
      email: rcannood@gmail.com
      roles: [ author, maintainer ]
      props: { github: rcannood, orcid: "0000-0003-3641-729X" }
  arguments:
    - name: "--input_prediction"
      type: "file"
      example: "prediction.h5ad"
      description: Prediction by a method.
      required: true
    - name: "--input_solution"
      type: "file"
      example: "solution.h5ad"
      description: Gold standard solution.
      required: true
    - name: "--output"
      type: "file"
      direction: "output"
      example: "output.h5ad"
      description: Metric scores by comparing the prediction to the gold standard solution.
      required: true
  resources:
    - type: r_script
      path: script.R
  tests:
    - type: python_script
      path: ../../unit_tests/test_metric.py
    - path: ../../../../resources_test
    - path: metric_meta_mse.tsv
      dest: metric_meta.tsv
platforms:
  - type: docker
    image: dataintuitive/randpy:r4.0_py3.8_bioc3.12
    setup: 
      - type: r
        github: 
          - dynverse/dynutils@devel
  - type: nextflow
