functionality:
  name: baseline_mnn
  namespace: joint_embedding_methods
  version: dev
  description: A baseline method for comparing joint embedding methods against.
  authors:
    - name: Robrecht Cannoodt
      email: rcannood@gmail.com
      roles: [ author, maintainer ]
      props: { github: rcannood, orcid: "0000-0003-3641-729X" }
  arguments:
    - name: "--input_mod1"
      type: "file"
      example: "dataset_mod1.h5ad"
      description: Censored dataset.
      required: true
    - name: "--input_mod2"
      type: "file"
      example: "dataset_mod2.h5ad"
      description: Censored dataset.
      required: true
    - name: "--output"
      type: "file"
      direction: "output"
      example: "output.h5ad"
      description: "The predicted pairing of test mod1&mod2 profiles."
      required: true
  resources:
    - type: r_script
      path: script.R
  tests:
    - type: r_script
      path: ../../unit_tests/test_method.R
    - path: ../../../../resources_test
platforms:
  - type: docker
    image: dataintuitive/randpy:r4.0_py3.8_bioc3.12
    setup:
      - type: r
        bioc: [ SingleCellExperiment, batchelor ]
  - type: nextflow
    labels: [ lowmem, lowtime, lowcpu ]
