functionality:
  name: baseline_knn
  namespace: predict_modality_methods
  version: dev
  description: A baseline method for comparing modality prediction methods against.
  authors:
    - name: Robrecht Cannoodt
      email: rcannood@gmail.com
      roles: [ author, maintainer ]
      props: { github: rcannood, orcid: "0000-0003-3641-729X" }
  arguments:
    - name: "--input_train_mod1"
      type: "file"
      example: "dataset_mod1.h5ad"
      description: Censored dataset, training cells.
      required: true
    - name: "--input_test_mod1"
      type: "file"
      example: "dataset_mod1.h5ad"
      description: Censored dataset, test cells.
      required: true
    - name: "--input_train_mod2"
      type: "file"
      example: "dataset_mod2.h5ad"
      description: Censored dataset.
      required: true
    - name: "--output"
      type: "file"
      direction: "output"
      example: "output.h5ad"
      description: Dataset with predicted values for modality2.
      required: true
    - name: "--distance_method"
      type: "string"
      default: "spearman"
      description: The distance method to use. Possible values are euclidean, pearson, spearman and others.
    - name: "--n_pcs"
      type: "integer"
      default: 4
      description: Number of principal components to use.
    - name: "--n_neighbors"
      type: "integer"
      default: 3
      description: Number of neighbors to use in the knn regression.
  resources:
    - type: r_script
      path: script.R
  tests:
    - type: r_script
      path: ../../unit_tests/test_method.R
    - path: ../../../../resources_test
platforms:
  - type: docker
    image: dataintuitive/randpy:r4.0_py3.8_bioc3.12
    setup:
      - type: r
        packages: [ lmds, FNN ]
  - type: nextflow
    labels: [ lowmem, lowtime, lowcpu ]
